# version: "3.9"

# services:
#   db:
#     image: mysql:8.0
#     container_name: messaging_db
#     restart: always
#     env_file: .env
#     ports:
#       - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql   # ✅ Persist database data here

#   web:
#     build: .
#     container_name: messaging_web
#     restart: always
#     command: python manage.py runserver 0.0.0.0:8000
#     env_file: .env
#     ports:
#       - "8000:8000"
#     depends_on:
#       - db
#     volumes:
#       - .:/app

# volumes:
#   mysql_data:   # ✅ Named volume definition
version: "3.9"

services:
  db:
    image: mysql:8.0
    container_name: messaging_db
    restart: always
    environment:
      MYSQL_USER: messaging_user
      MYSQL_DB: messaging_db
      MYSQL_PASSWORD: messaging_pass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build: .
    container_name: messaging_web
    restart: always
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      MYSQL_USER: messaging_user
      MYSQL_DB: messaging_db
      MYSQL_PASSWORD: messaging_pass
      MYSQL_ROOT_PASSWORD: rootpass
      DB_HOST: db
      DB_PORT: 3306
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  mysql_data:
